project:
  type: website
  
website:
  title: "Submissions WG Pilot 4"
  site-url: "https://rconsortium.github.io/submissions-pilot4"
  repo-url: "https://github.com/RConsortium/submissions-pilot4"
  repo-actions: [edit, issue]
  navbar:
    left:
      - href: index.qmd
        text: Home
      - minutes.qmd
      - text: "Learning Guide Resources"
        menu: 
          - href: tech_session.qmd
            text: Container Guide
          - href: docker_windows_setup.qmd
            text: Installing WSL & Docker Guide
      - text: "Site Development"
        menu: 
          - href: minutes_prep.qmd
            text: Minutes Draft Gen
    right:
      - icon: github
        href: https://github.com/RConsortium/submissions-pilot4
        aria-label: GitHub Site

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
    link-external-newwindow: true

execute: 
  freeze: auto