project:
  type: website
  output-dir: docs
  
website:
  title: "Submissions WG Pilot 4"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true



