---
title: "Introduction"
---

Welcome to the R Consortium R Submissions Pilot 4 documentation portal. You will find key materials, discussion notes, and additional information related to this pilot. To learn more about the submissions working group, please visit [rconsortium.github.io/submissions-wg/](https://rconsortium.github.io/submissions-wg/).

## Objective

Building upon the Submissions [Pilot 2](https://github.com/RConsortium/submissions-pilot2) in which a Shiny application created as an R package was successfully transferred to the FDA using the eCTD gateway protocol, the objective of Pilot 4 is to explore novel technologies to bundle the application along with the necessary execution dependencies and streamline the transfer and execution procedures. The specific technologies targeted in this pilot are the following:

* __Containers__: A mechanism to encapsulate a piece of software alongside the environment used for its dependencies and execution. The end user simply needs a container runtime installed on their system to execute a container.
* __WebAssembly__: A framework inspired by assembly in which applications developed in languages such as JavaScript, Python, and now R can be compiled into a self-contained native bundle that can be executed directly in a user's modern web browser, without requiring additional software on their host system.
