# output file
Output docker_ps_all_list.gif
Output docker_ps_all_list.mp4

# set up terminal size and font characteristics
Set FontSize 15
Set Width 2120
Set Width 1080

# set padding
Set Padding 20

# optional: set margin
#Set Margin 10
#Set MarginFill "#6B50FF"
#Set BorderRadius 10

# optional: set window bar
Set WindowBar ColorfulRight

# Set Theme
Set Theme "Tomorrow Night Eighties"

# Set typing speed
Set TypingSpeed 0.15

# execute docker ps -a
Show
Type "docker ps -a"
Enter

Sleep 5s
