# output file
Output docker_hello.gif
Output docker_hello.mp4

# set up terminal size and font characteristics
Set FontSize 20
Set Width 1920
Set Width 1080

# set padding
Set Padding 20

# optional: set margin
#Set Margin 10
#Set MarginFill "#6B50FF"
#Set BorderRadius 10

# optional: set window bar
Set WindowBar ColorfulRight

# Set Theme
Set Theme "Tomorrow Night Eighties"

# Set typing speed
Set TypingSpeed 0.2

# run docker hello-world
Show
Type "docker run hello-world"
Enter

Sleep 6s
