on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - '\.devcontainer/**'
      - '\.github/**'
      - 'README.md' 

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
        with:
          logger: pretty
          log-directives: nix_installer=trace
          backtrace: full

      - name: Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Build development environment
        run: |
          nix-build

      - name: Publish Site to Quarto Pub (custom)
        env:
          QUARTO_PUB_AUTH_TOKEN: ${{ secrets.QUARTO_PUB_AUTH_TOKEN }}
        run: |
          nix-shell --run "quarto publish --no-prompt --no-browser --id b915b535-6c33-4993-9889-835b0c4895be"
        shell: bash
